public class demoApex {
    public static void method1(){
        Boolean isActive = true;
        System.debug('Value of isActive ' +true);
    }
    public static void method2(){
        String fname= 'Kislay', lname ='Kashyap';
        System.debug('Name = '+ fname + ' ' + lname);                 
    }
    public static void method3(){
         Long mobNum = 6301400265L;
         System.debug('Mobile Number : '+ mobNum);
    }
    public static void method4(){
        ID accId ='001NS00000ZcrWZYAZ';
        System.debug('Id = ' + accId);
    }
}